### ISSUE TITLE
Nuget ?

### ISSUE THREAD

**Issue by ignatandrei** [dominikjeske/Samples#1]
I have an Roslyn Source COde Generators examples at https://github.com/ignatandrei/RSCG_Examples

I think that the example from https://dominikjeske.github.io/source-generators/ could be mentioned 

But I need that https://github.com/dominikjeske/Samples/tree/main/SourceGenerators  to be transformed into a nuget package to be used by others. 

What do you think ?

**Comment by dominikjeske** [comment]
I can prepare nuget if you find it helpfull. I can do it in the begining of July

**Comment by dominikjeske** [comment]
@ignatandrei I have updated my article with nuget information and mentioned your page in url section

**Comment by ignatandrei** [comment]
Sorry ofr answering so late. Do you have an example on GitHub with the nuget package ? I see a lot of possiblity, however, I need an example to start .

**Comment by dominikjeske** [comment]
I have switch to my nugets on my personal pet projct https://github.com/dominikjeske/HomeCenter/tree/MotionService/HomeCenter.SourceGenerators
